YOUTUBE_BASE_URL = "https://www.youtube.com"
YOUTUBE_SEARCH_URL = YOUTUBE_BASE_URL + "/results"

PUBLIC_YOUTUBE_API_KEY = "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8"
YOUTUBE_SEARCH_API = YOUTUBE_BASE_URL + "/youtubei/v1/search"
